version: '3'

services:
  db:
    image: postgres:alpine
    env_file:
      .env
  web:
    build: .
    command: gunicorn domoticz.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
